### ISSUE TITLE
code

### ISSUE THREAD

**Issue by chen-xihui** [jqueeney/geppo#3]
Can you comment your code more? For others, your code is a bit difficult to understand.

**Comment by chen-xihui** [comment]
In your code, there are many variables or abbreviations without clear description，which makes me feel confused.

**Comment by jqueeney** [comment]
We do not plan to make updates to code documentation at this time. Please note that any future updates will appear in the repository https://github.com/jqueeney/gpi.

**Comment by chen-xihui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
